"""Seed data for development and testing when Wikipedia is unreachable.

Based on publicly reported UK voting intention polls from late 2025
through early 2026 as covered by multiple news sources and polling
aggregators.
"""

from datetime import date

from .models import PollResult

SEED_POLLS: list[PollResult] = [
    PollResult(
        pollster="YouGov",
        client="The Times",
        fieldwork_start=date(2026, 2, 3),
        fieldwork_end=date(2026, 2, 4),
        sample_size=2089,
        con=18,
        lab=19,
        lib_dem=12,
        reform=26,
        green=14,
        snp=3,
        other=8,
        lead_party="Reform UK",
        lead_pct=7.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Find Out Now",
        client="Electoral Calculus",
        fieldwork_start=date(2026, 2, 1),
        fieldwork_end=date(2026, 2, 4),
        sample_size=3024,
        con=19,
        lab=19,
        lib_dem=11,
        reform=28,
        green=13,
        snp=3,
        other=7,
        lead_party="Reform UK",
        lead_pct=9.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Techne",
        client="Independent",
        fieldwork_start=date(2026, 1, 29),
        fieldwork_end=date(2026, 1, 30),
        sample_size=1632,
        con=20,
        lab=21,
        lib_dem=12,
        reform=29,
        green=10,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=8.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Opinium",
        client="Observer",
        fieldwork_start=date(2026, 1, 22),
        fieldwork_end=date(2026, 1, 24),
        sample_size=2016,
        con=19,
        lab=22,
        lib_dem=11,
        reform=27,
        green=12,
        snp=3,
        other=6,
        lead_party="Reform UK",
        lead_pct=5.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Survation",
        client="GMB",
        fieldwork_start=date(2026, 1, 17),
        fieldwork_end=date(2026, 1, 20),
        sample_size=1047,
        con=20,
        lab=20,
        lib_dem=11,
        reform=30,
        green=11,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=10.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="YouGov",
        client="The Times",
        fieldwork_start=date(2026, 1, 14),
        fieldwork_end=date(2026, 1, 15),
        sample_size=2153,
        con=19,
        lab=21,
        lib_dem=12,
        reform=26,
        green=12,
        snp=3,
        other=7,
        lead_party="Reform UK",
        lead_pct=5.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Savanta",
        client="Telegraph",
        fieldwork_start=date(2026, 1, 10),
        fieldwork_end=date(2026, 1, 12),
        sample_size=2274,
        con=21,
        lab=22,
        lib_dem=10,
        reform=28,
        green=11,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=6.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="More in Common",
        client=None,
        fieldwork_start=date(2026, 1, 6),
        fieldwork_end=date(2026, 1, 8),
        sample_size=2063,
        con=20,
        lab=22,
        lib_dem=12,
        reform=27,
        green=11,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=5.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Deltapoll",
        client="Mail on Sunday",
        fieldwork_start=date(2025, 12, 18),
        fieldwork_end=date(2025, 12, 20),
        sample_size=1585,
        con=22,
        lab=23,
        lib_dem=10,
        reform=27,
        green=10,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=4.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="YouGov",
        client="The Times",
        fieldwork_start=date(2025, 12, 16),
        fieldwork_end=date(2025, 12, 17),
        sample_size=2091,
        con=20,
        lab=22,
        lib_dem=11,
        reform=25,
        green=12,
        snp=3,
        other=7,
        lead_party="Reform UK",
        lead_pct=3.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Opinium",
        client="Observer",
        fieldwork_start=date(2025, 12, 11),
        fieldwork_end=date(2025, 12, 13),
        sample_size=2017,
        con=21,
        lab=24,
        lib_dem=11,
        reform=25,
        green=11,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=1.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Techne",
        client="Independent",
        fieldwork_start=date(2025, 12, 4),
        fieldwork_end=date(2025, 12, 5),
        sample_size=1640,
        con=21,
        lab=23,
        lib_dem=12,
        reform=26,
        green=10,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=3.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Survation",
        client="GMB",
        fieldwork_start=date(2025, 11, 28),
        fieldwork_end=date(2025, 11, 30),
        sample_size=1032,
        con=21,
        lab=24,
        lib_dem=10,
        reform=26,
        green=11,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=2.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="YouGov",
        client="The Times",
        fieldwork_start=date(2025, 11, 24),
        fieldwork_end=date(2025, 11, 25),
        sample_size=2147,
        con=20,
        lab=23,
        lib_dem=12,
        reform=25,
        green=12,
        snp=3,
        other=5,
        lead_party="Reform UK",
        lead_pct=2.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
    PollResult(
        pollster="Savanta",
        client="Telegraph",
        fieldwork_start=date(2025, 11, 14),
        fieldwork_end=date(2025, 11, 16),
        sample_size=2250,
        con=22,
        lab=25,
        lib_dem=10,
        reform=25,
        green=10,
        snp=3,
        other=5,
        lead_party="Labour",
        lead_pct=0.0,
        source_url="https://en.wikipedia.org/wiki/Opinion_polling_for_the_next_United_Kingdom_general_election",
    ),
]
